# Generated by Django 5.0.6 on 2024-06-22 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tisch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tisch_nummer', models.CharField(max_length=10, unique=True)),
                ('seats', models.IntegerField()),
                ('status', models.BooleanField(default=False)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
