# Generated by Django 5.0.6 on 2024-06-22 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tischs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_date', models.DateTimeField()),
                ('guest_count', models.IntegerField()),
                ('special_request', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='Confirmed', max_length=20)),
                ('tisch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tischs.tisch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
